
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 87
#define YY_END_OF_BUFFER 88
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[312] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       88,   86,    1,    2,    1,   31,   55,   24,   30,   40,
       32,   33,   23,   38,   23,   86,   24,   20,   39,   27,
       28,   27,   22,   36,   37,   30,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   34,   30,   35,
       54,   41,   54,   42,   54,   71,   56,   71,   70,   71,
       77,   73,   77,   76,   82,   80,   82,   82,    1,    2,
       27,   29,   25,   26,   21,   78,   72,   21,   20,   85,
       85,   30,   22,   22,   22,   22,   22,   22,    6,   22,
       22,   22,    3,   22,   22,   22,   22,   22,   22,   41,

       44,   43,   53,   47,   48,   51,   49,   45,   50,   46,
       52,   56,   58,    0,   60,   59,   69,   63,   64,   67,
       65,   61,   66,   62,   68,   73,   75,    0,   79,   81,
       83,   21,   85,   21,   85,   85,   85,    0,    0,   21,
       22,   22,   22,   22,   22,   22,   22,   22,    5,    9,
       22,   22,   22,   22,   22,   57,   74,   83,   83,   83,
       85,    0,   21,    0,   21,   21,   84,   84,   21,   85,
       22,   16,   10,   22,   22,   22,    4,   22,   22,   22,
       22,   13,   22,   83,   83,   83,   85,   83,   85,    0,
       21,   21,   21,   21,    0,   21,   21,   85,    0,   84,

       84,   85,    0,   84,    8,   22,   22,   22,   11,   22,
       22,   22,    7,   83,    0,   83,    0,   83,   85,    0,
       83,    0,   85,   21,   21,   21,   21,    0,    0,   85,
       85,    0,   84,   84,   85,    0,   84,   84,   22,   22,
       12,   22,   14,   15,    0,   83,   83,   85,    0,   83,
       85,    0,   83,   83,   83,    0,   85,   21,   85,    0,
        0,   85,   85,    0,   84,   84,   84,   22,   18,   19,
       85,    0,   83,    0,   83,   83,   83,   83,    0,   85,
        0,   85,    0,   84,   84,   84,   84,   17,    0,   83,
       83,   83,   83,   83,   83,    0,   85,    0,   84,   84,

       84,   83,   83,   83,   83,    0,   85,   84,   83,    0,
        0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   19,   19,    1,   20,   21,
       22,   23,    1,    1,   24,   24,   24,   24,   25,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       26,   27,   28,   29,   24,    1,   30,   31,   32,   33,

       34,   35,   24,   36,   37,   24,   38,   39,   24,   40,
       41,   42,   24,   43,   44,   45,   46,   47,   48,   24,
       24,   24,   49,   50,   51,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[52] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    2,    1,    3,    3,    1,
        1,    1,    1,    3,    3,    1,    1,    1,    1,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    1,    1,
        1
    } ;

static const flex_int16_t yy_base[319] =
    {   0,
        0,    0,   49,   51,   53,   58,   62,   64,   67,   69,
      572,  637,   73,  637,   80,  546,  637,  637,  550,  637,
      637,  637,  541,  637,  518,   68,   57,   74,  637,   73,
      507,   74,    0,  637,  637,  637,  480,   68,   66,  477,
       62,   70,  467,  472,  453,  458,  448,  637,  426,  637,
      637,  637,  467,  637,  105,  637,  637,  463,  637,  150,
      637,  637,  458,  109,  637,  637,  456,  435,  113,  637,
      637,  637,  637,  637,  100,  637,  637,  103,  108,  111,
      128,  637,    0,  412,  385,  396,  374,  376,  357,  355,
      354,  349,    0,  343,  343,  328,  329,  325,  322,  637,

      637,  637,  637,  637,  637,  637,  637,  637,  637,  637,
      637,  637,  637,  349,  637,  637,  637,  637,  637,  637,
      637,  637,  637,  637,  637,  637,  637,  347,  637,  637,
      139,  135,  148,  154,  181,  120,  156,  168,  164,  173,
      314,  306,  294,  287,  300,  297,  291,  283,    0,    0,
      271,  258,  256,  260,  250,  637,  637,  185,  190,  186,
      203,  194,  207,  209,  213,  217,  219,  221,  189,  230,
      245,    0,    0,  231,  219,  223,    0,  207,  202,  191,
      198,    0,  183,  238,  242,  225,  251,  255,  262,  266,
      260,  268,  272,  276,  280,  284,  280,  297,  304,  308,

        0,  316,  289,  302,    0,  138,  137,  137,    0,  126,
      122,  113,    0,  320,  328,  330,  338,  342,  350,  352,
      356,  359,  363,  365,  367,  371,  375,  379,  383,  397,
      405,  388,  403,  403,  412,  414,  420,  416,   85,   75,
        0,   66,    0,    0,  422,  424,  428,  432,  430,  436,
      445,  438,  449,  453,  455,  459,  461,  463,  470,  468,
      472,  476,  485,  478,  489,  493,  495,   68,    0,    0,
      502,  500,  506,  508,  512,  516,  518,  520,  522,  529,
      527,  531,  533,  537,  541,  543,  545,    0,  547,  551,
      555,  557,  561,  563,  565,  567,  571,  573,  577,  579,

      581,  585,  587,  589,  591,  595,  597,  599,  601,  603,
      637,  622,  625,  628,  631,  633,   85,   60
    } ;

static const flex_int16_t yy_def[319] =
    {   0,
      311,    1,  312,  312,  313,  313,  314,  314,  315,  315,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  316,  311,  311,
      311,  311,  317,  311,  311,  311,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  316,  311,  311,   75,   75,  318,
      318,  311,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  311,

      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,   75,  318,   75,  318,  318,  318,  311,  311,  318,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  311,  311,  311,   75,  159,
      318,  311,  140,  311,  318,  159,  311,  311,  140,  318,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  311,  311,  159,  318,  311,  318,  311,
      140,  166,  140,  316,  311,  140,  166,  318,  311,  166,

      200,  318,  311,  318,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  311,  311,  159,  311,  159,  318,  311,
      318,  311,  318,  166,  193,  166,  166,  200,  200,  318,
      318,  311,  311,  200,  318,  311,  318,  311,  317,  317,
      317,  317,  317,  317,  311,  311,  218,  318,  311,  311,
      318,  311,  318,  316,  196,  316,  196,  226,  318,  227,
      311,  318,  318,  311,  318,  316,  196,  317,  317,  317,
      318,  311,  318,  311,  318,  316,  196,  227,  227,  318,
      316,  196,  311,  318,  316,  196,  227,  317,  311,  318,
      316,  196,  316,  196,  227,  311,  318,  227,  316,  196,

      227,  316,  196,  227,  227,  316,  196,  227,  227,  227,
        0,  311,  311,  311,  311,  311,  311,  311
    } ;

static const flex_int16_t yy_nxt[689] =
    {   0,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   18,   23,   24,   25,   26,   27,   28,   28,   29,
       30,   31,   32,   33,   33,   34,   12,   35,   36,   33,
       37,   38,   39,   40,   41,   33,   42,   33,   33,   33,
       33,   43,   44,   45,   33,   33,   46,   47,   48,   49,
       50,   52,   53,   52,   53,   57,   58,   54,   59,   54,
       57,   58,  137,   59,   62,   63,   62,   63,   76,   66,
       67,   66,   67,   77,   69,   55,   69,   55,   68,   60,
       68,   69,   70,   69,   60,   75,   75,   83,   64,   78,
       64,   79,   79,   82,   71,   71,   82,   85,   81,   88,

       91,  288,   92,   86,   93,  270,   89,   81,   87,   94,
      101,  127,  128,  102,   69,  131,   69,  132,  132,  269,
      134,  134,  103,   78,  133,   79,   79,  135,  136,  136,
      268,  104,   81,  133,  105,  106,  135,  136,  136,  107,
      138,   81,  138,  139,  108,  140,  140,  109,  244,  110,
      160,  111,  113,  114,  158,  115,  159,  159,  116,  161,
      162,  243,  162,  139,  242,  163,  163,  117,  161,  160,
      241,  134,  134,  136,  136,  240,  118,  239,  161,  119,
      120,  167,  167,  139,  121,  166,  166,  161,  168,  122,
      169,  169,  123,  164,  124,  164,  125,  170,  165,  165,

      158,  188,  184,  184,  201,  185,  170,  186,  186,  139,
      189,  192,  192,  202,  187,  190,  213,  190,  139,  189,
      191,  191,  202,  187,  193,  193,  194,  194,  195,  212,
      196,  196,  168,  211,  197,  197,  167,  167,  200,  200,
      218,  198,  203,  199,  203,  199,  210,  204,  204,  219,
      198,  209,  199,  214,  199,  184,  184,  158,  219,  216,
      216,  208,  215,  220,  207,  220,  217,  206,  221,  221,
      158,  215,  216,  216,  222,  217,  222,  225,  225,  223,
      223,  139,  205,  224,  224,  226,  226,  201,  183,  193,
      193,  195,  182,  227,  227,  201,  202,  228,  228,  229,

      181,  196,  196,  180,  231,  202,  238,  238,  230,  203,
      179,  203,  178,  231,  204,  204,  232,  230,  232,  204,
      204,  233,  233,  195,  177,  234,  234,  176,  236,  175,
      236,  174,  235,  237,  237,  158,  173,  184,  184,  172,
      245,  235,  245,  171,  217,  246,  246,  247,  247,  157,
      249,  156,  249,  217,  248,  250,  250,  188,  155,  247,
      247,  154,  252,  248,  252,  153,  251,  253,  253,  254,
      254,  195,  152,  255,  255,  251,  256,  256,  195,  151,
      257,  257,  258,  258,  225,  225,  201,  150,  226,  226,
      229,  149,  227,  227,  148,  231,  260,  260,  147,  259,

      260,  260,  146,  189,  231,  233,  233,  189,  259,  261,
      145,  261,  189,  144,  262,  262,  189,  236,  229,  236,
      233,  233,  237,  237,  264,  143,  264,  263,  142,  265,
      265,  266,  266,  238,  238,  195,  263,  267,  267,  246,
      246,  246,  246,  218,  272,  141,  272,  250,  250,  273,
      273,  130,  271,  250,  250,  276,  276,  274,  129,  274,
      126,  271,  275,  275,  195,  112,  277,  277,  195,  100,
      278,  278,  255,  255,  195,   72,  279,  279,  257,  257,
      258,  258,  261,   99,  261,  260,  260,  262,  262,  281,
      281,  195,  280,  282,  282,  285,  285,  283,   98,  283,

       97,  280,  284,  284,  195,   96,  286,  286,  195,   95,
      287,  287,  267,  267,  289,   90,  289,  291,  291,  290,
      290,  195,   84,  292,  292,  293,  293,  195,   71,  294,
      294,  195,   74,  295,  295,  277,  277,  278,  278,  279,
      279,  296,  195,  296,  298,  298,  297,  297,  282,  282,
      299,  299,  195,   73,  300,  300,  195,   72,  301,  301,
      286,  286,  287,  287,  302,  302,  195,   71,  303,  303,
      195,  311,  304,  304,  292,  292,  195,  311,  305,  305,
      294,  294,  295,  295,  306,  306,  195,  311,  307,  307,
      298,  298,  195,  311,  308,  308,  300,  300,  301,  301,

      195,  311,  309,  309,  303,  303,  304,  304,  305,  305,
      195,  311,  310,  310,  307,  307,  308,  308,  309,  309,
      310,  310,   51,   51,   51,   56,   56,   56,   61,   61,
       61,   65,   65,   65,   80,   80,   11,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311
    } ;

static const flex_int16_t yy_chk[689] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    3,    4,    4,    5,    5,    3,    5,    4,
        6,    6,  318,    6,    7,    7,    8,    8,   27,    9,
        9,   10,   10,   27,   13,    3,   13,    4,    9,    5,
       10,   15,   15,   15,    6,   26,   26,  317,    7,   28,
        8,   28,   28,   30,   30,   32,   32,   38,   28,   39,

       41,  268,   41,   38,   42,  242,   39,   28,   38,   42,
       55,   64,   64,   55,   69,   75,   69,   75,   75,  240,
       78,   78,   55,   79,   75,   79,   79,   78,   80,   80,
      239,   55,   79,   75,   55,   55,   78,  136,  136,   55,
       81,   79,   81,   81,   55,   81,   81,   55,  212,   55,
      132,   55,   60,   60,  131,   60,  131,  131,   60,  132,
      133,  211,  133,  133,  210,  133,  133,   60,  132,  134,
      208,  134,  134,  137,  137,  207,   60,  206,  134,   60,
       60,  139,  139,  138,   60,  138,  138,  134,  140,   60,
      140,  140,   60,  135,   60,  135,   60,  140,  135,  135,

      158,  160,  158,  158,  169,  159,  140,  159,  159,  162,
      160,  162,  162,  169,  159,  161,  183,  161,  161,  160,
      161,  161,  169,  159,  163,  163,  164,  164,  165,  181,
      165,  165,  166,  180,  166,  166,  167,  167,  168,  168,
      186,  166,  170,  167,  170,  168,  179,  170,  170,  186,
      166,  178,  167,  184,  168,  184,  184,  185,  186,  185,
      185,  176,  184,  187,  175,  187,  185,  174,  187,  187,
      188,  184,  188,  188,  189,  185,  189,  191,  191,  189,
      189,  190,  171,  190,  190,  192,  192,  193,  155,  193,
      193,  194,  154,  194,  194,  197,  193,  195,  195,  196,

      153,  196,  196,  152,  197,  193,  203,  203,  196,  198,
      151,  198,  148,  197,  198,  198,  199,  196,  199,  204,
      204,  199,  199,  200,  147,  200,  200,  146,  202,  145,
      202,  144,  200,  202,  202,  214,  143,  214,  214,  142,
      215,  200,  215,  141,  214,  215,  215,  216,  216,  128,
      217,  114,  217,  214,  216,  217,  217,  218,   99,  218,
      218,   98,  219,  216,  219,   97,  218,  219,  219,  220,
      220,  221,   96,  221,  221,  218,  222,  222,  223,   95,
      223,  223,  224,  224,  225,  225,  226,   94,  226,  226,
      227,   92,  227,  227,   91,  226,  228,  228,   90,  227,

      229,  229,   89,  228,  226,  232,  232,  229,  227,  230,
       88,  230,  228,   87,  230,  230,  229,  231,  234,  231,
      233,  233,  231,  231,  235,   86,  235,  234,   85,  235,
      235,  236,  236,  238,  238,  237,  234,  237,  237,  245,
      245,  246,  246,  247,  248,   84,  248,  249,  249,  248,
      248,   68,  247,  250,  250,  252,  252,  251,   67,  251,
       63,  247,  251,  251,  253,   58,  253,  253,  254,   53,
      254,  254,  255,  255,  256,   49,  256,  256,  257,  257,
      258,  258,  259,   47,  259,  260,  260,  259,  259,  261,
      261,  262,  260,  262,  262,  264,  264,  263,   46,  263,

       45,  260,  263,  263,  265,   44,  265,  265,  266,   43,
      266,  266,  267,  267,  271,   40,  271,  272,  272,  271,
      271,  273,   37,  273,  273,  274,  274,  275,   31,  275,
      275,  276,   25,  276,  276,  277,  277,  278,  278,  279,
      279,  280,  281,  280,  281,  281,  280,  280,  282,  282,
      283,  283,  284,   23,  284,  284,  285,   19,  285,  285,
      286,  286,  287,  287,  289,  289,  290,   16,  290,  290,
      291,   11,  291,  291,  292,  292,  293,    0,  293,  293,
      294,  294,  295,  295,  296,  296,  297,    0,  297,  297,
      298,  298,  299,    0,  299,  299,  300,  300,  301,  301,

      302,    0,  302,  302,  303,  303,  304,  304,  305,  305,
      306,    0,  306,  306,  307,  307,  308,  308,  309,  309,
      310,  310,  312,  312,  312,  313,  313,  313,  314,  314,
      314,  315,  315,  315,  316,  316,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "1905118.l"




#line 9 "1905118.l"

#include <bits/stdc++.h>
using namespace std;

#include "1905118_symbol_table.h"
#include "y.tab.h"

extern YYSTYPE yylval;

// stringType 0 means single line str, 1 means mult line str
int stringType = 0, newlinesInMult = 0;

string charLiteralOriginal, charLiteralInterpreted;

string stringLiteralOriginal, stringLiteralInterpreted;

string commentOriginal;

extern ofstream logOut;
extern ofstream errorOut;

extern int lineCount;
extern int errorCount;

string capitaliseString(string s) {
    for(char &ch : s) {
        ch = toupper(ch);
    }
    return s;
}

#line 735 "lex.yy.c"
#line 736 "lex.yy.c"

#define INITIAL 0
#define STATE_CHAR_LITERAL 1
#define STATE_STRING_LITERAL 2
#define STATE_SINGLE_LINE_COMMENT 3
#define STATE_MULT_LINE_COMMENT 4

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 52 "1905118.l"


#line 960 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 312 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 637 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 54 "1905118.l"
{}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 56 "1905118.l"
{lineCount++;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 58 "1905118.l"
{
    SymbolInfo* symbolInfo = new SymbolInfo(yytext, "IF");
    symbolInfo->setRuleStartLine(lineCount);
    symbolInfo->setRuleEndLine(lineCount);
    symbolInfo->setLeafNodeStatus(true);
    yylval.symbolInfo = symbolInfo;
    logOut << "Line# " << lineCount << ": Token <" << capitaliseString(yytext) << "> Lexeme " << yytext <<" found\n";
    return IF;
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 68 "1905118.l"
{
    SymbolInfo* symbolInfo = new SymbolInfo(yytext, "ELSE");
    symbolInfo->setRuleStartLine(lineCount);
    symbolInfo->setRuleEndLine(lineCount);
    symbolInfo->setLeafNodeStatus(true);
    yylval.symbolInfo = symbolInfo;
    logOut << "Line# " << lineCount << ": Token <" << capitaliseString(yytext) << "> Lexeme " << yytext <<" found\n";
    return ELSE;
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 78 "1905118.l"
{
    SymbolInfo* symbolInfo = new SymbolInfo(yytext, "FOR");
    symbolInfo->setRuleStartLine(lineCount);
    symbolInfo->setRuleEndLine(lineCount);
    symbolInfo->setLeafNodeStatus(true);
    yylval.symbolInfo = symbolInfo;
    logOut << "Line# " << lineCount << ": Token <" << capitaliseString(yytext) << "> Lexeme " << yytext <<" found\n";
    return FOR;
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 88 "1905118.l"
{
    SymbolInfo* symbolInfo = new SymbolInfo(yytext, "DO");
    symbolInfo->setRuleStartLine(lineCount);
    symbolInfo->setRuleEndLine(lineCount);
    symbolInfo->setLeafNodeStatus(true);
    yylval.symbolInfo = symbolInfo;
    logOut << "Line# " << lineCount << ": Token <" << capitaliseString(yytext) << "> Lexeme " << yytext <<" found\n";
    return DO;
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 98 "1905118.l"
{
    SymbolInfo* symbolInfo = new SymbolInfo(yytext, "WHILE");
    symbolInfo->setRuleStartLine(lineCount);
    symbolInfo->setRuleEndLine(lineCount);
    symbolInfo->setLeafNodeStatus(true);
    yylval.symbolInfo = symbolInfo;
    logOut << "Line# " << lineCount << ": Token <" << capitaliseString(yytext) << "> Lexeme " << yytext <<" found\n";
    return WHILE;
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 108 "1905118.l"
{
    SymbolInfo* symbolInfo = new SymbolInfo(yytext, "BREAK");
    symbolInfo->setRuleStartLine(lineCount);
    symbolInfo->setRuleEndLine(lineCount);
    symbolInfo->setLeafNodeStatus(true);
    yylval.symbolInfo = symbolInfo;
    logOut << "Line# " << lineCount << ": Token <" << capitaliseString(yytext) << "> Lexeme " << yytext <<" found\n";
    return BREAK;
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 118 "1905118.l"
{
    SymbolInfo* symbolInfo = new SymbolInfo(yytext, "INT");
    symbolInfo->setRuleStartLine(lineCount);
    symbolInfo->setRuleEndLine(lineCount);
    symbolInfo->setLeafNodeStatus(true);
    yylval.symbolInfo = symbolInfo;
    logOut << "Line# " << lineCount << ": Token <" << capitaliseString(yytext) << "> Lexeme " << yytext <<" found\n";
    return INT;
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 128 "1905118.l"
{
    SymbolInfo* symbolInfo = new SymbolInfo(yytext, "CHAR");
    symbolInfo->setRuleStartLine(lineCount);
    symbolInfo->setRuleEndLine(lineCount);
    symbolInfo->setLeafNodeStatus(true);
    yylval.symbolInfo = symbolInfo;
    logOut << "Line# " << lineCount << ": Token <" << capitaliseString(yytext) << "> Lexeme " << yytext <<" found\n";
    return CHAR;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 138 "1905118.l"
{
    SymbolInfo* symbolInfo = new SymbolInfo(yytext, "FLOAT");
    symbolInfo->setRuleStartLine(lineCount);
    symbolInfo->setRuleEndLine(lineCount);
    symbolInfo->setLeafNodeStatus(true);
    yylval.symbolInfo = symbolInfo;
    logOut << "Line# " << lineCount << ": Token <" << capitaliseString(yytext) << "> Lexeme " << yytext <<" found\n";
    return FLOAT;
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 148 "1905118.l"
{
    SymbolInfo* symbolInfo = new SymbolInfo(yytext, "DOUBLE");
    symbolInfo->setRuleStartLine(lineCount);
    symbolInfo->setRuleEndLine(lineCount);
    symbolInfo->setLeafNodeStatus(true);
    yylval.symbolInfo = symbolInfo;
    logOut << "Line# " << lineCount << ": Token <" << capitaliseString(yytext) << "> Lexeme " << yytext <<" found\n";
    return DOUBLE;
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 158 "1905118.l"
{
    SymbolInfo* symbolInfo = new SymbolInfo(yytext, "VOID");
    symbolInfo->setRuleStartLine(lineCount);
    symbolInfo->setRuleEndLine(lineCount);
    symbolInfo->setLeafNodeStatus(true);
    yylval.symbolInfo = symbolInfo;
    logOut << "Line# " << lineCount << ": Token <" << capitaliseString(yytext) << "> Lexeme " << yytext <<" found\n";
    return VOID;
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 168 "1905118.l"
{
    SymbolInfo* symbolInfo = new SymbolInfo(yytext, "RETURN");
    symbolInfo->setRuleStartLine(lineCount);
    symbolInfo->setRuleEndLine(lineCount);
    symbolInfo->setLeafNodeStatus(true);
    yylval.symbolInfo = symbolInfo;
    logOut << "Line# " << lineCount << ": Token <" << capitaliseString(yytext) << "> Lexeme " << yytext <<" found\n";
    return RETURN;
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 178 "1905118.l"
{
    SymbolInfo* symbolInfo = new SymbolInfo(yytext, "SWITCH");
    symbolInfo->setRuleStartLine(lineCount);
    symbolInfo->setRuleEndLine(lineCount);
    symbolInfo->setLeafNodeStatus(true);
    yylval.symbolInfo = symbolInfo;
    logOut << "Line# " << lineCount << ": Token <" << capitaliseString(yytext) << "> Lexeme " << yytext <<" found\n";
    return SWITCH;
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 188 "1905118.l"
{
    SymbolInfo* symbolInfo = new SymbolInfo(yytext, "CASE");
    symbolInfo->setRuleStartLine(lineCount);
    symbolInfo->setRuleEndLine(lineCount);
    symbolInfo->setLeafNodeStatus(true);
    yylval.symbolInfo = symbolInfo;
    logOut << "Line# " << lineCount << ": Token <" << capitaliseString(yytext) << "> Lexeme " << yytext <<" found\n";
    return CASE;
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 198 "1905118.l"
{
    SymbolInfo* symbolInfo = new SymbolInfo(yytext, "CONTINUE");
    symbolInfo->setRuleStartLine(lineCount);
    symbolInfo->setRuleEndLine(lineCount);
    symbolInfo->setLeafNodeStatus(true);
    yylval.symbolInfo = symbolInfo;
    logOut << "Line# " << lineCount << ": Token <" << capitaliseString(yytext) << "> Lexeme " << yytext <<" found\n";
    return CONTINUE;
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 208 "1905118.l"
{
    SymbolInfo* symbolInfo = new SymbolInfo(yytext, "DEFAULT");
    symbolInfo->setRuleStartLine(lineCount);
    symbolInfo->setRuleEndLine(lineCount);
    symbolInfo->setLeafNodeStatus(true);
    yylval.symbolInfo = symbolInfo;
    logOut << "Line# " << lineCount << ": Token <" << capitaliseString(yytext) << "> Lexeme " << yytext <<" found\n";
    return DEFAULT;
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 218 "1905118.l"
{
    SymbolInfo* symbolInfo = new SymbolInfo(yytext, "PRNTLN");
    symbolInfo->setRuleStartLine(lineCount);
    symbolInfo->setRuleEndLine(lineCount);
    symbolInfo->setLeafNodeStatus(true);
    yylval.symbolInfo = symbolInfo;
    logOut << "Line# " << lineCount << ": Token <" << capitaliseString(yytext) << "> Lexeme " << yytext <<" found\n";
    return PRNTLN;
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 228 "1905118.l"
{
                    // tokenOut << "<" << "CONST_INT" << ", " << yytext << ">\n";
                    // logOut << "Line# " << lineCount << ": Token <" << "CONST_INT" << "> Lexeme " << yytext <<" found\n";
                    SymbolInfo* symbolInfo = new SymbolInfo(yytext, "CONST_INT");
                    symbolInfo->setRuleStartLine(lineCount);
                    symbolInfo->setRuleEndLine(lineCount);
                    symbolInfo->setLeafNodeStatus(true);
                    symbolInfo->setDataType("INT");
                    yylval.symbolInfo = symbolInfo;
                    logOut << "Line# " << lineCount << ": Token <" << "CONST_INT" << "> Lexeme " << yytext <<" found\n";
                    return CONST_INT;
                    // return CONST_INT;
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 242 "1905118.l"
{
                    // tokenOut << "<" << "CONST_FLOAT" << ", " << yytext << ">\n";
                    // logOut << "Line# " << lineCount << ": Token <" << "CONST_FLOAT" << "> Lexeme " << yytext <<" found\n";
                    SymbolInfo* symbolInfo = new SymbolInfo(yytext, "CONST_FLOAT");
                    symbolInfo->setRuleStartLine(lineCount);
                    symbolInfo->setRuleEndLine(lineCount);
                    symbolInfo->setLeafNodeStatus(true);
                    symbolInfo->setDataType("FLOAT");
                    yylval.symbolInfo = symbolInfo;
                    logOut << "Line# " << lineCount << ": Token <" << "CONST_FLOAT" << "> Lexeme " << yytext <<" found\n";
                    return CONST_FLOAT;
                    // return CONST_FLOAT;
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 256 "1905118.l"
{  
                    // need to insert to symtable
                    // tokenOut << "<" << "ID" << ", " << yytext << ">\n";
                    // logOut << "Line# " << lineCount << ": Token <" << "ID" << "> Lexeme " << yytext <<" found\n";
                    // SymbolInfo *symbol = new SymbolInfo(yytext, "ID");
                    // if(symbolTable->insertSymbolInSymbolTable(symbol, logOut)) {
                    //     symbolTable->printAllScopeTables(logOut);
                    // }
                    // else {
                    //     delete symbol;
                    // }
                    SymbolInfo* symbolInfo = new SymbolInfo(yytext, "ID");
                    symbolInfo->setRuleStartLine(lineCount);
                    symbolInfo->setRuleEndLine(lineCount);
                    symbolInfo->setLeafNodeStatus(true);
                    yylval.symbolInfo = symbolInfo;
                    logOut << "Line# " << lineCount << ": Token <" << "ID" << "> Lexeme " << yytext <<" found\n";
                    return ID;
                    // return ID;
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 277 "1905118.l"
{
                    // tokenOut << "<" << "ADDOP" << ", " << yytext << ">\n";
                    // logOut << "Line# " << lineCount << ": Token <" << "ADDOP" << "> Lexeme " << yytext <<" found\n";
                    SymbolInfo* symbolInfo = new SymbolInfo(yytext, "ADDOP");
                    symbolInfo->setRuleStartLine(lineCount);
                    symbolInfo->setRuleEndLine(lineCount);
                    symbolInfo->setLeafNodeStatus(true);
                    yylval.symbolInfo = symbolInfo;
                    logOut << "Line# " << lineCount << ": Token <" << "ADDOP" << "> Lexeme " << yytext <<" found\n";
                    return ADDOP;
                    // return ADDOP;
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 290 "1905118.l"
{
                    // tokenOut << "<" << "MULOP" << ", " << yytext << ">\n";
                    // logOut << "Line# " << lineCount << ": Token <" << "MULOP" << "> Lexeme " << yytext <<" found\n";
                    SymbolInfo* symbolInfo = new SymbolInfo(yytext, "MULOP");
                    symbolInfo->setRuleStartLine(lineCount);
                    symbolInfo->setRuleEndLine(lineCount);
                    symbolInfo->setLeafNodeStatus(true);
                    yylval.symbolInfo = symbolInfo;
                    logOut << "Line# " << lineCount << ": Token <" << "MULOP" << "> Lexeme " << yytext <<" found\n";
                    return MULOP;
                    // return MULOP;
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 303 "1905118.l"
{
                    // tokenOut << "<" << "INCOP" << ", " << yytext << ">\n";
                    // logOut << "Line# " << lineCount << ": Token <" << "INCOP" << "> Lexeme " << yytext <<" found\n";
                    SymbolInfo* symbolInfo = new SymbolInfo(yytext, "INCOP");
                    symbolInfo->setRuleStartLine(lineCount);
                    symbolInfo->setRuleEndLine(lineCount);
                    symbolInfo->setLeafNodeStatus(true);
                    yylval.symbolInfo = symbolInfo;
                    logOut << "Line# " << lineCount << ": Token <" << "INCOP" << "> Lexeme " << yytext <<" found\n";
                    return INCOP;
                    // return INCOP;
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 316 "1905118.l"
{
                    // tokenOut << "<" << "INCOP" << ", " << yytext << ">\n";
                    // logOut << "Line# " << lineCount << ": Token <" << "DECOP" << "> Lexeme " << yytext <<" found\n";
                    SymbolInfo* symbolInfo = new SymbolInfo(yytext, "DECOP");
                    symbolInfo->setRuleStartLine(lineCount);
                    symbolInfo->setRuleEndLine(lineCount);
                    symbolInfo->setLeafNodeStatus(true);
                    yylval.symbolInfo = symbolInfo;
                    logOut << "Line# " << lineCount << ": Token <" << "DECOP" << "> Lexeme " << yytext <<" found\n";
                    return DECOP;
                    // return DECOP;
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 329 "1905118.l"
{
                    // tokenOut << "<" << "RELOP" << ", " << yytext << ">\n";
                    // logOut << "Line# " << lineCount << ": Token <" << "RELOP" << "> Lexeme " << yytext <<" found\n";
                    SymbolInfo* symbolInfo = new SymbolInfo(yytext, "RELOP");
                    symbolInfo->setRuleStartLine(lineCount);
                    symbolInfo->setRuleEndLine(lineCount);
                    symbolInfo->setLeafNodeStatus(true);
                    yylval.symbolInfo = symbolInfo;
                    logOut << "Line# " << lineCount << ": Token <" << "RELOP" << "> Lexeme " << yytext <<" found\n";
                    return RELOP;
                    // return RELOP;
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 342 "1905118.l"
{
                    // tokenOut << "<" << "ASSIGNOP" << ", " << yytext << ">\n";
                    // logOut << "Line# " << lineCount << ": Token <" << "ASSIGNOP" << "> Lexeme " << yytext <<" found\n";
                    SymbolInfo* symbolInfo = new SymbolInfo(yytext, "ASSIGNOP");
                    symbolInfo->setRuleStartLine(lineCount);
                    symbolInfo->setRuleEndLine(lineCount);
                    symbolInfo->setLeafNodeStatus(true);
                    yylval.symbolInfo = symbolInfo;
                    logOut << "Line# " << lineCount << ": Token <" << "ASSIGNOP" << "> Lexeme " << yytext <<" found\n";
                    return ASSIGNOP;
                    // return ASSIGNOP;
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 355 "1905118.l"
{
                    // tokenOut << "<" << "LOGICOP" << ", " << yytext << ">\n";
                    // logOut << "Line# " << lineCount << ": Token <" << "LOGICOP" << "> Lexeme " << yytext <<" found\n";
                    SymbolInfo* symbolInfo = new SymbolInfo(yytext, "LOGICOP");
                    symbolInfo->setRuleStartLine(lineCount);
                    symbolInfo->setRuleEndLine(lineCount);
                    symbolInfo->setLeafNodeStatus(true);
                    yylval.symbolInfo = symbolInfo;
                    logOut << "Line# " << lineCount << ": Token <" << "LOGICOP" << "> Lexeme " << yytext <<" found\n";
                    return LOGICOP;
                    // return LOGICOP;
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 368 "1905118.l"
{
                    // tokenOut << "<" << "BITOP" << ", " << yytext << ">\n";
                    // logOut << "Line# " << lineCount << ": Token <" << "BITOP" << "> Lexeme " << yytext <<" found\n";
                    SymbolInfo* symbolInfo = new SymbolInfo(yytext, "BITOP");
                    symbolInfo->setRuleStartLine(lineCount);
                    symbolInfo->setRuleEndLine(lineCount);
                    symbolInfo->setLeafNodeStatus(true);
                    yylval.symbolInfo = symbolInfo;
                    logOut << "Line# " << lineCount << ": Token <" << "BITOP" << "> Lexeme " << yytext <<" found\n";
                    return BITOP;
                    // return BITOP;
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 381 "1905118.l"
{
                    // tokenOut << "<" << "NOT" << ", " << yytext << ">\n";
                    // logOut << "Line# " << lineCount << ": Token <" << "NOT" << "> Lexeme " << yytext <<" found\n";
                    SymbolInfo* symbolInfo = new SymbolInfo(yytext, "NOT");
                    symbolInfo->setRuleStartLine(lineCount);
                    symbolInfo->setRuleEndLine(lineCount);
                    symbolInfo->setLeafNodeStatus(true);
                    yylval.symbolInfo = symbolInfo;
                    logOut << "Line# " << lineCount << ": Token <" << "NOT" << "> Lexeme " << yytext <<" found\n";
                    return NOT;
                    // return NOT;
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 394 "1905118.l"
{
                    // tokenOut << "<" << "LPAREN" << ", " << yytext << ">\n";
                    // logOut << "Line# " << lineCount << ": Token <" << "LPAREN" << "> Lexeme " << yytext <<" found\n";
                    SymbolInfo* symbolInfo = new SymbolInfo(yytext, "LPAREN");
                    symbolInfo->setRuleStartLine(lineCount);
                    symbolInfo->setRuleEndLine(lineCount);
                    symbolInfo->setLeafNodeStatus(true);
                    yylval.symbolInfo = symbolInfo;
                    logOut << "Line# " << lineCount << ": Token <" << "LPAREN" << "> Lexeme " << yytext <<" found\n";
                    return LPAREN;
                    // return LPAREN;
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 407 "1905118.l"
{
                    // tokenOut << "<" << "RPAREN" << ", " << yytext << ">\n";
                    // logOut << "Line# " << lineCount << ": Token <" << "RPAREN" << "> Lexeme " << yytext <<" found\n";
                    SymbolInfo* symbolInfo = new SymbolInfo(yytext, "RPAREN");
                    symbolInfo->setRuleStartLine(lineCount);
                    symbolInfo->setRuleEndLine(lineCount);
                    symbolInfo->setLeafNodeStatus(true);
                    yylval.symbolInfo = symbolInfo;
                    logOut << "Line# " << lineCount << ": Token <" << "RPAREN" << "> Lexeme " << yytext <<" found\n";
                    return RPAREN;
                    // return RPAREN;
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 420 "1905118.l"
{
                    // need to enter scope
                    // symbolTable->enterScope(scopeTableCounter++, num_of_buckets);
                    // tokenOut << "<" << "LCURL" << ", " << yytext << ">\n";
                    // logOut << "Line# " << lineCount << ": Token <" << "LCURL" << "> Lexeme " << yytext <<" found\n";
                    SymbolInfo* symbolInfo = new SymbolInfo(yytext, "LCURL");
                    symbolInfo->setRuleStartLine(lineCount);
                    symbolInfo->setRuleEndLine(lineCount);
                    symbolInfo->setLeafNodeStatus(true);
                    yylval.symbolInfo = symbolInfo;
                    logOut << "Line# " << lineCount << ": Token <" << "LCURL" << "> Lexeme " << yytext <<" found\n";
                    return LCURL;
                    // return LCURL;
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 435 "1905118.l"
{
                    // need to exit scope
                    // symbolTable->exitScope();
                    // tokenOut << "<" << "RCURL" << ", " << yytext << ">\n";
                    // logOut << "Line# " << lineCount << ": Token <" << "RCURL" << "> Lexeme " << yytext <<" found\n";
                    SymbolInfo* symbolInfo = new SymbolInfo(yytext, "RCURL");
                    symbolInfo->setRuleStartLine(lineCount);
                    symbolInfo->setRuleEndLine(lineCount);
                    symbolInfo->setLeafNodeStatus(true);
                    yylval.symbolInfo = symbolInfo;
                    logOut << "Line# " << lineCount << ": Token <" << "RCURL" << "> Lexeme " << yytext <<" found\n";
                    return RCURL;
                    // return RCURL;
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 450 "1905118.l"
{
                    // tokenOut << "<" << "LSQUARE" << ", " << yytext << ">\n";
                    // logOut << "Line# " << lineCount << ": Token <" << "LSQUARE" << "> Lexeme " << yytext <<" found\n";
                    SymbolInfo* symbolInfo = new SymbolInfo(yytext, "LSQUARE");
                    symbolInfo->setRuleStartLine(lineCount);
                    symbolInfo->setRuleEndLine(lineCount);
                    symbolInfo->setLeafNodeStatus(true);
                    yylval.symbolInfo = symbolInfo;
                    logOut << "Line# " << lineCount << ": Token <" << "LSQUARE" << "> Lexeme " << yytext <<" found\n";
                    return LSQUARE;
                    // return LSQUARE;
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 463 "1905118.l"
{
                    // tokenOut << "<" << "RSQUARE" << ", " << yytext << ">\n";
                    // logOut << "Line# " << lineCount << ": Token <" << "RSQUARE" << "> Lexeme " << yytext <<" found\n";
                    SymbolInfo* symbolInfo = new SymbolInfo(yytext, "RSQUARE");
                    symbolInfo->setRuleStartLine(lineCount);
                    symbolInfo->setRuleEndLine(lineCount);
                    symbolInfo->setLeafNodeStatus(true);
                    yylval.symbolInfo = symbolInfo;
                    logOut << "Line# " << lineCount << ": Token <" << "RSQUARE" << "> Lexeme " << yytext <<" found\n";
                    return RSQUARE;
                    // return RSQUARE;
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 476 "1905118.l"
{
                    // tokenOut << "<" << "COMMA" << ", " << yytext << ">\n";
                    // logOut << "Line# " << lineCount << ": Token <" << "COMMA" << "> Lexeme " << yytext <<" found\n";
                    SymbolInfo* symbolInfo = new SymbolInfo(yytext, "COMMA");
                    symbolInfo->setRuleStartLine(lineCount);
                    symbolInfo->setRuleEndLine(lineCount);
                    symbolInfo->setLeafNodeStatus(true);
                    yylval.symbolInfo = symbolInfo;
                    logOut << "Line# " << lineCount << ": Token <" << "COMMA" << "> Lexeme " << yytext <<" found\n";
                    return COMMA;
                    // return COMMA;
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 489 "1905118.l"
{
                    // tokenOut << "<" << "SEMICOLON" << ", " << yytext << ">\n";
                    // logOut << "Line# " << lineCount << ": Token <" << "SEMICOLON" << "> Lexeme " << yytext <<" found\n";
                    SymbolInfo* symbolInfo = new SymbolInfo(yytext, "SEMICOLON");
                    symbolInfo->setRuleStartLine(lineCount);
                    symbolInfo->setRuleEndLine(lineCount);
                    symbolInfo->setLeafNodeStatus(true);
                    yylval.symbolInfo = symbolInfo;
                    logOut << "Line# " << lineCount << ": Token <" << "SEMICOLON" << "> Lexeme " << yytext <<" found\n";
                    return SEMICOLON;
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 501 "1905118.l"
{
    charLiteralOriginal.clear();
    charLiteralInterpreted.clear();
    BEGIN STATE_CHAR_LITERAL;
}
	YY_BREAK
case YY_STATE_EOF(STATE_CHAR_LITERAL):
#line 507 "1905118.l"
{
    errorCount++;
    charLiteralOriginal = "'" + charLiteralOriginal;
    logOut << "Error at line# " << lineCount << ": UNFINISHED_CONST_CHAR " << charLiteralOriginal << '\n';
    BEGIN INITIAL;
}
	YY_BREAK
case 41:
/* rule 41 can match eol */
YY_RULE_SETUP
#line 514 "1905118.l"
{
    errorCount++;
    charLiteralOriginal = "'" + charLiteralOriginal;
    logOut << "Error at line# " << lineCount << ": UNFINISHED_CONST_CHAR " << charLiteralOriginal << '\n';
    lineCount++;
    BEGIN INITIAL;
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 522 "1905118.l"
{
    charLiteralOriginal = "'" + charLiteralOriginal + "'";
    if(charLiteralInterpreted.size() == 0) {
        if(charLiteralOriginal == "'\0'") {
            // tokenOut << "<" << "CONST_CHAR" << ", " << charLiteralInterpreted << ">\n";
            logOut << "Line# " << lineCount << ": Token <" << "CONST_CHAR" << "> Lexeme " << charLiteralInterpreted <<" found\n";
        }
        else {
            errorCount++;
            logOut << "Error at line# " << lineCount << ": EMPTY_CONST_CHAR " << charLiteralOriginal << '\n';
        }
    }
    else if(charLiteralInterpreted.size() == 1) {
        // tokenOut << "<" << "CONST_CHAR" << ", " << charLiteralInterpreted << ">\n";
        logOut << "Line# " << lineCount << ": Token <" << "CONST_CHAR" << "> Lexeme " << charLiteralInterpreted <<" found\n";
    }
    else {
        errorCount++;
        logOut << "Error at line# " << lineCount << ": MULTICHAR_CONST_CHAR " << charLiteralOriginal << '\n';
    }
    BEGIN INITIAL;
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 545 "1905118.l"
{
    charLiteralOriginal += "\\\'";
    charLiteralInterpreted += "\'";
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 550 "1905118.l"
{
    charLiteralOriginal += "\\\"";
    charLiteralInterpreted += "\"";
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 555 "1905118.l"
{
    charLiteralOriginal += "\\n";
    charLiteralInterpreted += "\n";
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 560 "1905118.l"
{
    charLiteralOriginal += "\\t";
    charLiteralInterpreted += "\t";
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 565 "1905118.l"
{
    charLiteralOriginal += "\\\\";
    charLiteralInterpreted += "\\";
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 570 "1905118.l"
{
    charLiteralOriginal += "\\a";
    charLiteralInterpreted += "\a";
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 575 "1905118.l"
{
    charLiteralOriginal += "\\f";
    charLiteralInterpreted += "\f";
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 580 "1905118.l"
{
    charLiteralOriginal += "\\r";
    charLiteralInterpreted += "\r";
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 585 "1905118.l"
{
    charLiteralOriginal += "\\b";
    charLiteralInterpreted += "\b";
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 590 "1905118.l"
{
    charLiteralOriginal += "\\v";
    charLiteralInterpreted += "\v";
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 595 "1905118.l"
{
    charLiteralOriginal += "\\0";
    charLiteralInterpreted += "\0";
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 600 "1905118.l"
{
    charLiteralOriginal += yytext[0];
    charLiteralInterpreted += yytext[0];
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 605 "1905118.l"
{
    stringLiteralOriginal.clear();
    stringLiteralInterpreted.clear();
    BEGIN STATE_STRING_LITERAL;
}
	YY_BREAK
case YY_STATE_EOF(STATE_STRING_LITERAL):
#line 611 "1905118.l"
{
    errorCount++;
    stringLiteralOriginal = "\"" + stringLiteralOriginal;
    logOut << "Error at line# " << lineCount + newlinesInMult << ": UNFINISHED_STRING " << stringLiteralOriginal << '\n';
    stringType = 0;
    newlinesInMult = 0;
    BEGIN INITIAL;
}
	YY_BREAK
case 56:
/* rule 56 can match eol */
YY_RULE_SETUP
#line 620 "1905118.l"
{
    errorCount++;
    stringLiteralOriginal = "\"" + stringLiteralOriginal;
    logOut << "Error at line# " << lineCount + newlinesInMult << ": UNFINISHED_STRING " << stringLiteralOriginal << '\n';
    lineCount += newlinesInMult + 1;
    stringType = 0;
    newlinesInMult = 0;
    BEGIN INITIAL;
}
	YY_BREAK
case 57:
/* rule 57 can match eol */
YY_RULE_SETUP
#line 630 "1905118.l"
{
    stringType = 1;
    newlinesInMult++;
    stringLiteralOriginal += "\\\r\n";
}
	YY_BREAK
case 58:
/* rule 58 can match eol */
YY_RULE_SETUP
#line 636 "1905118.l"
{
    stringType = 1;
    newlinesInMult++;
    stringLiteralOriginal += "\\\n";
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 642 "1905118.l"
{
    stringLiteralOriginal += "\\\'";
    stringLiteralInterpreted += "\'";
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 647 "1905118.l"
{
    stringLiteralOriginal += "\\\"";
    stringLiteralInterpreted += "\"";
}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 652 "1905118.l"
{
    stringLiteralOriginal += "\\n";
    stringLiteralInterpreted += "\n";
}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 657 "1905118.l"
{
    stringLiteralOriginal += "\\t";
    stringLiteralInterpreted += "\t";
}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 662 "1905118.l"
{
    stringLiteralOriginal += "\\\\";
    stringLiteralInterpreted += "\\";
}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 667 "1905118.l"
{
    stringLiteralOriginal += "\\a";
    stringLiteralInterpreted += "\a";
}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 672 "1905118.l"
{
    stringLiteralOriginal += "\\f";
    stringLiteralInterpreted += "\f";
}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 677 "1905118.l"
{
    stringLiteralOriginal += "\\r";
    stringLiteralInterpreted += "\r";
}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 682 "1905118.l"
{
    stringLiteralOriginal += "\\b";
    stringLiteralInterpreted += "\b";
}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 687 "1905118.l"
{
    stringLiteralOriginal += "\\v";
    stringLiteralInterpreted += "\v";
}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 692 "1905118.l"
{
    stringLiteralOriginal += "\\0";
    stringLiteralInterpreted += "\0";
}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 697 "1905118.l"
{
    stringLiteralOriginal = "\"" + stringLiteralOriginal + "\"";
    string STRING = (stringType == 0) ? "SINGLE LINE STRING" : "MULTI LINE STRING";
    // tokenOut << "<" << STRING << ", " << stringLiteralInterpreted << ">\n";
    logOut << "Line# " << lineCount << ": Token <" << STRING << "> Lexeme " << stringLiteralOriginal <<" found\n";
    lineCount += newlinesInMult;
    newlinesInMult = 0;
    stringType = 0;
    BEGIN INITIAL;
}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 708 "1905118.l"
{
    stringLiteralOriginal += yytext[0];
    stringLiteralInterpreted += yytext[0];
}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 713 "1905118.l"
{
    commentOriginal.clear();
    commentOriginal += "//";
    newlinesInMult = 0;
    BEGIN STATE_SINGLE_LINE_COMMENT;
}
	YY_BREAK
case YY_STATE_EOF(STATE_SINGLE_LINE_COMMENT):
#line 721 "1905118.l"
{
    logOut << "Line# " << lineCount << ": Token <" << "SINGLE LINE COMMENT" << "> Lexeme " << commentOriginal <<" found\n";
    lineCount += newlinesInMult;
    newlinesInMult = 0;
    BEGIN INITIAL;
}
	YY_BREAK
case 73:
/* rule 73 can match eol */
YY_RULE_SETUP
#line 728 "1905118.l"
{
    newlinesInMult++;
    logOut << "Line# " << lineCount << ": Token <" << "SINGLE LINE COMMENT" << "> Lexeme " << commentOriginal <<" found\n";
    lineCount += newlinesInMult;
    newlinesInMult = 0;
    BEGIN INITIAL;
}
	YY_BREAK
case 74:
/* rule 74 can match eol */
YY_RULE_SETUP
#line 736 "1905118.l"
{
    newlinesInMult++;
    commentOriginal += "\\\r\n";
}
	YY_BREAK
case 75:
/* rule 75 can match eol */
YY_RULE_SETUP
#line 741 "1905118.l"
{
    newlinesInMult++;
    commentOriginal += "\\\n";
}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 747 "1905118.l"
{
    commentOriginal += "\\";
}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 751 "1905118.l"
{
    commentOriginal += yytext[0];
}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 755 "1905118.l"
{
    commentOriginal.clear();
    commentOriginal += "/*";
    newlinesInMult = 0;
    BEGIN STATE_MULT_LINE_COMMENT;
}
	YY_BREAK
case YY_STATE_EOF(STATE_MULT_LINE_COMMENT):
#line 763 "1905118.l"
{
    errorCount++;
    lineCount += newlinesInMult;
    logOut << "Error at line# " << lineCount << ": UNFINISHED_COMMENT " << commentOriginal << "\n";
    newlinesInMult = 0;
    BEGIN INITIAL;
}
	YY_BREAK
case 79:
/* rule 79 can match eol */
YY_RULE_SETUP
#line 771 "1905118.l"
{
    commentOriginal += "\r\n";
    newlinesInMult++;
}
	YY_BREAK
case 80:
/* rule 80 can match eol */
YY_RULE_SETUP
#line 776 "1905118.l"
{
    commentOriginal += "\n";
    newlinesInMult++;
}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 781 "1905118.l"
{
    commentOriginal += "*/";
    logOut << "Line# " << lineCount << ": Token <" << "MULTI LINE COMMENT" << "> Lexeme " << commentOriginal <<" found\n";
    lineCount += newlinesInMult;
    newlinesInMult = 0;
    BEGIN INITIAL;
}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 789 "1905118.l"
{
    commentOriginal += yytext[0];
}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 793 "1905118.l"
{
    errorCount++;
    logOut << "Error at line# " << lineCount << ": TOO_MANY_DECIMAL_POINTS " << yytext << '\n';
    // return TOO_MANY_DECIMAL_POINTS;
}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 799 "1905118.l"
{
    errorCount++;
    logOut << "Error at line# " << lineCount << ": ILLFORMED_NUMBER " << yytext << '\n';
    // return ILLFORMED_NUMBER;
}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 805 "1905118.l"
{
    errorCount++;
    logOut << "Error at line# " << lineCount << ": INVALID_ID_SUFFIX_NUM_PREFIX " << yytext << '\n';
    // return INVALID_ID_SUFFIX_NUM_PREFIX;
}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 811 "1905118.l"
{
   errorCount++;
   logOut << "Error at line# " << lineCount << ": UNRECOGNIZED_CHAR " << yytext << '\n';
    // return UNRECOGNIZED_CHAR;
}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 817 "1905118.l"
ECHO;
	YY_BREAK
#line 2058 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 312 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 312 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 311);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 817 "1905118.l"


// int main(int argc, char *argv[]) {
//     if(argc != 2) {
//         cout << "Please provide input file name and try again\n";
//         return 0;
//     }

//     FILE *inputFile = fopen(argv[1], "r");
//     if(inputFile == NULL) {
//         cout << "Cannot open specified file\n";
//         return 0;
//     }

//     tokenOut.open("1905118_token.txt");
//     logOut.open("1905118_log.txt");

//     symbolTable->enterScope(scopeTableCounter++, num_of_buckets);

//     yyin = inputFile;
//     yylex();
//     fclose(yyin);

//     symbolTable->printAllScopeTables(logOut);

    // logOut << "Total lines: " << lineCount << '\n';
    // logOut << "Total errors: " << errorCount << '\n';

//     delete symbolTable;

//     tokenOut.close();
//     logOut.close();

//     return 0;
// }
